spring.application.name=streakup

spring.datasource.url=${DB_URL:jdbc:postgresql://127.0.0.1:5433/streakup}
spring.datasource.username=${DB_USERNAME:streakup}
spring.datasource.password=${DB_PASSWORD:streakup_dev_password}

jwt.secret=${JWT_SECRET:RhqcxAH0i5MxzVm5Iu5OP6MhIHRMawmM9oGFX/sifPM=}
jwt.expiration-minutes=${JWT_EXPIRATION_MINUTES:1440}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
app.timezone=${APP_TIMEZONE:UTC}
