spring.application.name=streakup

spring.datasource.url=${DB_URL:jdbc:postgresql://127.0.0.1:5433/streakup}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

jwt.secret=${JWT_SECRET}
jwt.expiration-minutes=1440

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true